spring:
  application:
    name: datacollector
  main:
    web-application-type: none

  datasource:
    url: "jdbc:h2:file:${H2_DATABASE_PATH:/app/data/price-monitor};DB_CLOSE_ON_EXIT=FALSE"
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver

    hikari:
      pool-name: PriceCollector-HikariPool
      maximum-pool-size: ${DB_POOL_MAX_SIZE:1}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    open-in-view: false

collector:
  enabled: "${COLLECTOR_ENABLED:true}"
logging:
  level:
    root: INFO
    org.springframework.data: INFO
    com.scarlxrd.datacollector: ${COLLECTOR_LOG_LEVEL:INFO}